apiVersion: 1

datasources:
  - name: PostgreSQL
    type: grafana-postgresql-datasource
    uid: PCC52D03280B7034C
    access: proxy
    url: postgres:5432
    database: pipeline_db
    user: ipbd_user
    secureJsonData:
      password: ipbd_pass
    jsonData:
      database: pipeline_db
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    isDefault: true
