[MLflow]
tracking_uri = http://mlflow:5000
backend_store_uri = postgresql://ipbd_user:ipbd_pass@postgres:5432/pipeline_db
default_artifact_root = s3://mlflow-artifacts/
s3_endpoint_url = http://minio:9000

[Experiment]
name = gold_price_forecasting
tags = project:ipbd, team:kelompok10

[ModelRegistry]
model_name = gold_price_predictor
description = Model forecasting harga emas nasional
