apiVersion: 1

notifiers:
  - name: Telegram Alert
    type: telegram
    uid: telegram-notifier
    is_default: true
    settings:
      bottoken: "8683547942:AAFoJRDrsFzaI4yghNw0uMghwVAfXvACRA0"
      chatid: "5519545800"
      parse_mode: "HTML"
      disable_notifications: false
